
SET(CMAKE_C_COMPILER  /usr/bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER  /usr/bin/x86_64-w64-mingw32-g++)

SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_FIND_ROOT_PATH  /home/beto0607/UnNivelMas-Workspace/OnePuch/ /home/beto0607/Programacion/Libs/SDL/Windows/)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)